---
apiVersion: 'helm.fluxcd.io/v1'
kind: 'HelmRelease'
metadata:
  name: 'home-assistant'
  namespace: 'default'
  annotations:
    fluxcd.io/automated: 'true'
spec:
  releaseName: 'home-assistant'
  chart:
    repository: 'https://billimek.com/billimek-charts/'
    name: 'home-assistant'
    version: '1.0.1'
