---
apiVersion: 'helm.fluxcd.io/v1'
kind: 'HelmRelease'
metadata:
  name: 'cert-manager'
  namespace: 'cert-manager'
  annotations:
    filter.fluxcd.io/cainjector: 'semver:*'
    filter.fluxcd.io/chart-image: 'semver:*'
    filter.fluxcd.io/webhook: 'semver:*'
    fluxcd.io/automated: 'true'
spec:
  chart:
    repository: 'https://charts.jetstack.io'
    name: 'cert-manager'
    version: 'v0.16.0'
  releaseName: 'cert-manager'
  values:
    cainjector:
      image:
        repository: 'quay.io/jetstack/cert-manager-cainjector'
        tag: 'v0.16.0'
    extraArgs:
      - '--dns01-recursive-nameservers=1.1.1.1:53'
      - '--dns01-recursive-nameservers-only'
    global:
      logLevel: 2
    image:
      repository: 'quay.io/jetstack/cert-manager-controller'
      tag: 'v0.16.0'
    installCRDs: true
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
    webhook:
      image:
        repository: 'quay.io/jetstack/cert-manager-webhook'
        tag: 'v0.16.0'
