---
apiVersion: 'cert-manager.io/v1alpha2'
kind: 'ClusterIssuer'
metadata:
  name: 'letsencrypt'
spec:
  acme:
    email: 'josh@joshuaspence.com'
    server: 'https://acme-staging-v02.api.letsencrypt.org/directory'
    privateKeySecretRef:
      name: 'letsencrypt-staging'
    solvers:
      - dns01:
          route53:
            region: 'ap-southeast-2'
            hostedZoneID: 'Z8WQJGKO99WMI'
            accessKeyID: 'AKIAUFWWWHZD52ZSO6WC'
            secretAccessKeySecretRef:
              name: 'route53-iam'
              key: 'secret-access-key'
        selector:
          dnsZones:
            - 'spence.network'
