---
apiVersion: 'helm.fluxcd.io/v1'
kind: 'HelmRelease'
metadata:
  name: 'flux'
  namespace: 'flux'
  annotations:
    filter.fluxcd.io/chart-image: 'semver:*'
    filter.fluxcd.io/memcached: 'semver:*'
    fluxcd.io/automated: 'true'
    repository.fluxcd.io/memcached: 'memcached.repository'
    tag.fluxcd.io/memcached: 'memcached.tag'
spec:
  chart:
    repository: 'https://charts.fluxcd.io'
    name: 'flux'
    version: '1.4.0'
  releaseName: 'flux'
  values:
    dashboards:
      enabled: true
    git:
      branch: 'master'
      path: 'src'
      secretName: 'flux-git-deploy'
      url: 'git@github.com:joshuaspence/homelab.git'
    gpgKeys:
      secretName: 'flux-gpg'
    image:
      repository: 'docker.io/fluxcd/flux'
      tag: '1.20.1'
    memcached:
      repository: 'memcached'
      tag: '1.6.6'
    prometheus:
      enabled: true
      serviceMonitor:
        create: true
    sops:
      enabled: true
    syncGarbageCollection:
      enabled: true
