---
apiVersion: 'helm.fluxcd.io/v1'
kind: 'HelmRelease'
metadata:
  name: 'flux'
  namespace: 'flux'
  annotations:
    fluxcd.io/automated: 'false'
spec:
  chart:
    repository: 'https://charts.fluxcd.io'
    name: 'flux'
    version: '1.4.0'
  releaseName: 'flux'
  values:
    git:
      branch: 'master'
      path: 'src'
      secretName: 'flux-git-deploy'
      url: 'git@github.com:joshuaspence/homelab.git'
    image:
      repository: 'docker.io/fluxcd/flux'
      tag: '1.20.0'
    syncGarbageCollection:
      enabled: true
