---
apiVersion: 'helm.fluxcd.io/v1'
kind: 'HelmRelease'
metadata:
  name: 'flux-web'
  namespace: 'flux'
spec:
  chart:
    git: 'https://github.com/flux-web/flux-web.git'
    ref: 'master'
    path: 'chart/flux-web'
  releaseName: 'flux-web'
  values:
    backend:
      repository: 'fluxweb/backend'
      tag: '0.1'
    frontend:
      env:
        API_EXTERNAL_URL: '//flux-web.spence.network/api/v1'
        WS_URL: 'wss://flux-web.spence.network/ws/v1'
      repository: 'fluxweb/frontend'
      tag: '0.1'
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: 'letsencrypt'
      hosts:
        - host: 'flux-web.spence.network'
          paths:
            - frontend: '/'
            - backend: '/api'
            - backend: '/ws'
      tls:
        - hosts:
            - 'flux-web.spence.network'
          secretName: 'flux-web-tls'
    readOnly: false
