---
apiVersion: 'helm.fluxcd.io/v1'
kind: 'HelmRelease'
metadata:
  annotations:
    filter.fluxcd.io/chart-image: 'semver:*'
    fluxcd.io/automated: 'true'
  name: 'helm-operator'
  namespace: 'flux'
spec:
  chart:
    name: 'helm-operator'
    repository: 'https://charts.fluxcd.io'
    version: '1.2.0'
  releaseName: 'helm-operator'
  values:
    dashboards:
      enabled: true
    git:
      ssh:
        secretName: 'flux-git-deploy'
    helm:
      versions: 'v3'
    image:
      repository: 'docker.io/fluxcd/helm-operator'
      tag: '1.2.0'
    prometheus:
      enabled: true
      serviceMonitor:
        create: true
