---
apiVersion: 'helm.fluxcd.io/v1'
kind: 'HelmRelease'
metadata:
  name: 'helm-operator'
  namespace: 'flux'
  annotations:
    fluxcd.io/automated: 'true'
    filter.fluxcd.io/chart-image: 'semver:*'
spec:
  chart:
    repository: 'https://charts.fluxcd.io'
    name: 'helm-operator'
    version: '1.1.0'
  releaseName: 'helm-operator'
  values:
    image:
      repository: 'docker.io/fluxcd/helm-operator'
      tag: '1.2.0'
    git:
      ssh:
        secretName: 'flux-git'
    helm:
      versions: 'v3'
    prometheus:
      enabled: true
      serviceMonitor:
        create: true
    dashboards:
      enabled: true
