---
apiVersion: 'helm.fluxcd.io/v1'
kind: 'HelmRelease'
metadata:
  name: 'helm-operator'
  namespace: 'flux'
  annotations:
    fluxcd.io/automated: 'true'
spec:
  chart:
    repository: 'https://charts.fluxcd.io'
    name: 'helm-operator'
    version: '1.1.0'
  releaseName: 'helm-operator'
  values:
    git:
      ssh:
        secretName: 'flux-git-deploy'
    helm:
      versions: 'v3'
