# yamllint disable rule:key-ordering
---
extends: 'default'

rules:
  braces:
    forbid: 'non-empty'
    min-spaces-inside: 1
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
  brackets:
    forbid: 'non-empty'
  comments:
    level: 'error'
  comments-indentation:
    level: 'error'
  document-end:
    present: false
  document-start:
    level: 'error'
  empty-lines:
    max: 1
  empty-values: 'enable'
  indentation:
    spaces: 2
  key-ordering: 'enable'
  octal-values: 'enable'
  quoted-strings:
    quote-type: 'single'
  truthy:
    check-keys: false
    level: 'error'
