---
default: true

heading-style:
  style: 'atx'
ul-style:
  style: 'dash'
ol-prefix:
  style: 'ordered'
hr-style:
  style: '---'
code-block-style:
  style: 'fenced'
code-fence-style:
  style: 'backtick'
