---
apiVersion: 'helm.fluxcd.io/v1'
kind: 'HelmRelease'
metadata:
  annotations:
    fluxcd.io/automated: 'true'
    fluxcd.io/tag.grafana: 'semver:~7'
    fluxcd.io/tag.prometheusOperator: 'semver:~0'
  name: 'prometheus'
  namespace: 'monitoring'
spec:
  chart:
    name: 'kube-prometheus-stack'
    repository: 'https://prometheus-community.github.io/helm-charts'
    version: '9.4.5'
  releaseName: 'prometheus'
  values:
    alertmanager:
      alertmanagerSpec:
        image:
          repository: 'quay.io/prometheus/alertmanager'
          tag: 'v0.21.0'
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: 'letsencrypt'
        enabled: true
        hosts: &alertmanager_hosts
        - 'alertmanager.spence.network'
        tls:
        - hosts: *alertmanager_hosts
          secretName: 'alertmanager-tls'
    grafana:
      image:
        repository: 'grafana/grafana'
        tag: '7.2.1'
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: 'letsencrypt'
        enabled: true
        hosts: &grafana_hosts
        - 'grafana.spence.network'
        tls:
        - hosts: *grafana_hosts
          secretName: 'grafana-tls'
      sidecar:
        dashboards:
          enabled: true
          searchNamespace: 'ALL'
          watchMethod: 'WATCH'
        datasources:
          enabled: true
          searchNamespace: 'ALL'
    prometheus:
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: 'letsencrypt'
        enabled: true
        hosts: &prometheus_hosts
        - 'prometheus.spence.network'
        tls:
        - hosts: *prometheus_hosts
          secretName: 'prometheus-tls'
      prometheusSpec:
        image:
          repository: 'quay.io/prometheus/prometheus'
          tag: 'v2.18.2'
        podMonitorSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
      thanosIngress:
        annotations:
          cert-manager.io/cluster-issuer: 'letsencrypt'
        enabled: true
        hosts: &thanos_hosts
        - 'thanos.spence.network'
        tls:
        - hosts: *thanos_hosts
          secretName: 'thanos-tls'
    prometheusOperator:
      image:
        repository: 'quay.io/coreos/prometheus-operator'
        tag: 'v0.42.1'
      prometheusConfigReloaderImage:
        repository: 'quay.io/coreos/prometheus-config-reloader'
        tag: 'v0.38.1'
