---
apiVersion: 'helm.fluxcd.io/v1'
kind: 'HelmRelease'
metadata:
  name: 'prometheus-operator'
  namespace: 'monitoring'
  annotations:
    fluxcd.io/automated: 'true'
    fluxcd.io/tag.grafana: 'semver:~7'
    fluxcd.io/tag.prometheusOperator: 'semver:~0'
spec:
  chart:
    repository: 'https://kubernetes-charts.storage.googleapis.com'
    name: 'prometheus-operator'
    version: '9.3.1'
  releaseName: 'prometheus-operator'
  values:
    prometheusOperator:
      image:
        repository: 'quay.io/coreos/prometheus-operator'
        tag: 'v0.41.1'
      prometheusConfigReloaderImage:
        repository: 'quay.io/coreos/prometheus-config-reloader'
        tag: 'v0.38.1'
    prometheus:
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: 'letsencrypt'
        enabled: true
        hosts:
        - 'prometheus.spence.network'
        tls:
        - hosts:
          - 'prometheus.spence.network'
          secretName: 'prometheus-tls'
      prometheusSpec:
        image:
          repository: 'quay.io/prometheus/prometheus'
          tag: 'v2.18.2'
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
      thanosIngress:
        annotations:
          cert-manager.io/cluster-issuer: 'letsencrypt'
        enabled: true
        hosts:
        - 'thanos.spence.network'
        tls:
        - hosts:
          - 'thanos.spence.network'
          secretName: 'thanos-tls'
    alertmanager:
      alertmanagerSpec:
        image:
          repository: 'quay.io/prometheus/alertmanager'
          tag: 'v0.21.0'
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: 'letsencrypt'
        enabled: true
        hosts:
        - 'alertmanager.spence.network'
        tls:
        - hosts:
          - 'alertmanager.spence.network'
          secretName: 'alertmanager-tls'
    grafana:
      image:
        repository: 'grafana/grafana'
        tag: '7.1.3'
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: 'letsencrypt'
        enabled: true
        hosts:
        - 'grafana.spence.network'
        tls:
        - hosts:
          - 'grafana.spence.network'
          secretName: 'grafana-tls'
      sidecar:
        dashboards:
          enabled: true
          watchMethod: 'WATCH'
          searchNamespace: 'ALL'
        datasources:
          enabled: true
          searchNamespace: 'ALL'
