---
apiVersion: 'helm.fluxcd.io/v1'
kind: 'HelmRelease'
metadata:
  name: 'external-dns'
  namespace: 'kube-system'
spec:
  chart:
    name: 'external-dns'
    repository: 'https://charts.bitnami.com/bitnami'
    version: '3.2.5'
  releaseName: 'external-dns'
  values:
    crd:
      create: true
    image:
      repository: 'bitnami/external-dns'
      tag: '0.7.2'
    logLevel: 'debug'
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    provider: 'aws'
    zoneIdFilters: ['Z8WQJGKO99WMI']
  valuesFrom:
    - secretKeyRef:
        name: 'external-dns-aws'
