---
apiVersion: 'helm.fluxcd.io/v1'
kind: 'HelmRelease'
metadata:
  annotations:
    filter.fluxcd.io/controller: 'semver:~0'
    filter.fluxcd.io/speaker: 'semver:~0'
    fluxcd.io/automated: 'true'
  name: 'metallb'
  namespace: 'kube-system'
spec:
  chart:
    name: 'metallb'
    repository: 'https://charts.bitnami.com/bitnami'
    version: '0.1.27'
  releaseName: 'metallb'
  values:
    configInline:
      address-pools:
      - addresses:
        - '172.100.1.0/24'
        name: 'default'
        protocol: 'layer2'
    controller:
      image:
        repository: 'bitnami/metallb-controller'
        tag: '0.9.4'
    prometheus:
      enabled: true
      prometheusRule:
        enabled: true
      serviceMonitor:
        enabled: true
    speaker:
      image:
        repository: 'bitnami/metallb-speaker'
        tag: '0.9.4'
