---
apiVersion: 'helm.fluxcd.io/v1'
kind: 'HelmRelease'
metadata:
  annotations:
    fluxcd.io/automated: 'false'
  name: 'nginx-ingress'
  namespace: 'kube-system'
spec:
  chart:
    name: 'ingress-nginx'
    repository: 'https://kubernetes.github.io/ingress-nginx'
    version: '3.3.0'
  releaseName: 'nginx-ingress'
  values:
    controller:
      autoscaling:
        enabled: false
      dnsPolicy: 'ClusterFirst'
      healthCheckPath: '/healthz'
      hostNetwork: false
      hostPort:
        enabled: true
        ports:
          http: 80
          https: 443
      metrics:
        enabled: true
        prometheusRule:
          enabled: false
        serviceMonitor:
          enabled: false
      reportNodeInternalIp: false
      service:
        internal:
          enabled: false
    defaultBackend:
      enabled: false
