---
apiVersion: 'helm.fluxcd.io/v1'
kind: 'HelmRelease'
metadata:
  name: 'nginx-ingress'
  namespace: 'kube-system'
spec:
  releaseName: 'nginx-ingress'
  chart:
    repository: 'https://kubernetes.github.io/ingress-nginx'
    name: 'ingress-nginx'
    version: '2.11.2'
  values:
    controller:
      hostNetwork: false
      dnsPolicy: 'ClusterFirst'
      reportNodeInternalIp: false
      healthCheckPath: '/healthz'
      autoscaling:
        enabled: false
      hostPort:
        enabled: true
        ports:
          http: 80
          https: 443
      service:
        internal:
          enabled: false
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
        prometheusRule:
          enabled: false
    defaultBackend:
      enabled: false
