---
apiVersion: 'v1'
kind: 'Secret'
metadata:
  name: 'external-dns-aws'
  namespace: 'kube-system'
data:
  values.yaml: 'ENC[AES256_GCM,data:YD08qGwN0+zoRnzbNnAYr/BN17iOTU6KVaKQp0hztISqUE+LJcQfu+WjIAlM6JTV8pet7uDAklaFobmB8ajSjWOdTlBnzjqRQ/QAAJvy735/dkIwXpHY2XsTxZTn1ykGA2F3muXLyg7IYDPyzLj24l46+icUwrq9H6G4ddK+1HnzALUb1nvA6qUm642WkOzVx6T0EUkq9cPzb0ZEmamz,iv:K8fHYsW7gnQ7aDEZveuYOjefnfZMZDow31OQ7bJSduk=,tag:hwHX/XRaVIkgdBc+MPZbMw==,type:str]'
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  lastmodified: '2020-08-05T03:08:29Z'
  mac: 'ENC[AES256_GCM,data:SWShjvM+Yz13tfJMJUD0rYHL3kdP6HFpx2pmFtq9Uz9Wm6xh4pf29J3GWHYkmpu8V28LNNnyOgd4EJ+HlCmRKsD0xfiRGsLcNARMa5DiLrZOJP6RumRP+AY/DXPq5KAUXVEjRDhGBhW7HMCEwZRZO91LaiR6ETP83aff9h8G8fk=,iv:7CR7AZsZHovbJB02z2TPHZ82WQ5F0R2OBoofle5qEQA=,tag:j9L9GfoKa6g3EKhh6wyxLQ==,type:str]'
  pgp:
    - created_at: '2020-08-05T03:08:28Z'
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMAwfWukh8FXBAAQ/+Lq9ZQmBOErFiam2idyNqqDXjEwAg7u5+33qpzLr73GYp
        rVMOGPRjobooUkpw1d/6amoqfXljAUFKo6GUWoFstGDrp884k3/EiX8YMK0ogvce
        UjpqNg8RmB+wlCAfVLfT3hNalWPibefvBOGGySTLZuVDnYaXx1gCcUbwrmwc0ukX
        OIQLSesM0s8Y77DEMCrkGRqvoIjeLndgXL/5ifTR2GCephFdfwxhrGMYsBqdCAsa
        z+YNgkF+rZMngrJtn1dkF+cEHUkWRZuGB1blYy2VaGjy0pW0Ur2O/XeAturUEZUu
        aSbxleDLYAqQ6IJ+PiMGu7hqIc20+RWrmCWrQRGZuaaOPpG6intnNKAB1VOICdje
        50PWyHGWt23A5oHtdkNR0ET9Vvml4Jp9eUQTmBWXdWy6kowM+6WBZnEtgVxCUgBy
        ZTP1w15y8H+5YVCu0G5jFjLsbhpZ7prhauSCeXJQ+l2eyiNRkgMVVYPqQnIdM4UJ
        x1gbnA7+3qzxP0rmzNYMlpgJ1ExqKH4A6QdEEbHqGh1B8zb/KlHz9o+obI0xsMSx
        urz1poVb+ehmIiLkICqXt7TegJJUUn8C6E44nUtHV9QmijilbRH0qFVz5nKQoOa2
        FM+y1u+JZcSEziTR3ODAnmYWa1oI+bphDx1RLhhm7gGMxhUhCJsWgI87CuS6vL7S
        XgE3LM236WFh89ZYgImPUEjhbc6eaEb4iSbWwNCOLtekiykSPnP6e74HY/Ts/s5N
        QlhGZJD3pTPhg2SHY2g0VZrWXIGID9ngbVya5fu7UvasM5sUbEsU6+iGyJQH79Y=
        =BcfM
        -----END PGP MESSAGE-----
        fp: 7A9A7C3C477E67A2
    - created_at: '2020-08-05T03:08:28Z'
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMA35r/HGpJBTzAQ//ZrW9ZARkLrpw/3rBQaw1cLWZyauPJuFuF6+uQd03ITCS
        y3jBsEFMAQpzUz572M49g88seGVStm/SZpCdqAG/7DPxPcUx9OpkWFfYH0ezH198
        EmcFw/kc1l0N0zo1AJ7hqTQjpIMR37tl8YKihbBoXv0Mkv+sN8c0INp7e/tfm2Na
        1sujCNKRPoHOTbscMiE6Yy8jK785do0OpRoJ4QOSKAmydKrtdFHTsV0N2Snyo6Ex
        GY0ScX9UpR9+SCwPwgV2DHkOah+yPBcazGvQtM7ZvH2aeL+YjI1pDYI4bxOdga7E
        wm0qir4PqsLvK1wEZHssk/Ehu2pRjt8qLlfLt2D6W4go/nI4rLjNGHFFl17LIXFi
        +mVOWnFgHrZ5ElY497lE5pLUlrCYOnmZALjCPLskmq4cnKjYhsdB+AUHO60J8amt
        hhJhJvvjcPPG1vHbUY+0tTS/dNb8Is8gBZ+lfLaA1Rm2yloDeTcu1gm9wX+L0ac2
        s2rbGc2hH4nNe3jhUBq7CPIXhgJPzksX+S/f4qx9QmnfpiZtbtWQ/4hKbT8KN0mq
        mxEvDpupbmvhcVLU3p6qTy7f+2HeohFM+go0DAt8XsKicNc+or4xytiNWfGQCrHT
        ABC+R115g8CwirHQqJqxbSByySL7OpLf0aQ3PfZ4n6qwHcPTEkBY9n9/rhcgIG/S
        XgEf2D1yfv+BjzWHlk8mJVySRgcjtMu/n6Ju2ez0vuwzpZ4IwkdhbNFddVD/LdZU
        GyEcs/4YRuirMQqbrHOUMOj2uXasT2QRGZCaxVHkXWhNtVEpANcthJrD7Pk7Uek=
        =zRCI
        -----END PGP MESSAGE-----
      fp: '31F9EEC019716222'
  encrypted_regex: '^(data)$'
  version: '3.6.0'
