---
apiVersion: 'helm.fluxcd.io/v1'
kind: 'HelmRelease'
metadata:
  name: 'nginx-ingress'
  namespace: 'kube-system'
  annotations:
    fluxcd.io/ignore: 'false'
    fluxcd.io/automated: 'false'
spec:
  releaseName: 'nginx-ingress'
  chart:
    name: 'ingress-nginx'
    version: '1.40.3'
  values:
    controller:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
        prometheusRule:
          rules: []
