---
apiVersion: 'helm.fluxcd.io/v1'
kind: 'HelmRelease'
metadata:
  name: 'nginx-ingress'
  namespace: 'kube-system'
spec:
  releaseName: 'nginx-ingress'
  chart:
    repository: 'https://kubernetes-charts.storage.googleapis.com/'
    name: 'ingress-nginx'
    version: '1.40.3'
  values:
    controller:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
        prometheusRule:
          rules: []
