---
apiVersion: 'helm.fluxcd.io/v1'
kind: 'HelmRelease'
metadata:
  annotations:
    filter.fluxcd.io/chart-image: 'semver:~0'
    fluxcd.io/automated: 'true'
  name: 'home-assistant'
  namespace: 'default'
spec:
  chart:
    name: 'home-assistant'
    repository: 'https://k8s-at-home.com/charts'
    version: '2.5.0'
  releaseName: 'home-assistant'
  values:
    git:
      enabled: true
      repo: 'git@github.com:joshuaspence/home-assistant-config.git'
      secret: 'git-creds'
    hostNetwork: false
    image:
      repository: 'homeassistant/home-assistant'
      tag: '0.116.4'
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: 'letsencrypt'
      enabled: true
      hosts: &hosts
        - 'hass.spence.network'
      tls:
        - hosts: *hosts
          secretName: 'home-assistant-tls'
    monitoring:
      enabled: true
      serviceMonitor:
        enabled: true
