---
apiVersion: 'helm.fluxcd.io/v1'
kind: 'HelmRelease'
metadata:
  name: 'home-assistant'
  namespace: 'default'
  annotations:
    fluxcd.io/automated: 'true'
    fluxcd.io/tag.chart-image: 'semver:~0.'
spec:
  chart:
    repository: 'https://billimek.com/billimek-charts/'
    name: 'home-assistant'
    version: '1.0.1'
  releaseName: 'home-assistant'
  values:
    image:
      repository: 'homeassistant/home-assistant'
      tag: '0.112.4'
    ingress:
      enabled: true
      hosts:
      - 'home-assistant.local'
    monitoring:
      enabled: true
      serviceMonitor:
        enabled: true
