---
apiVersion: 'helm.fluxcd.io/v1'
kind: 'HelmRelease'
metadata:
  annotations:
    filter.fluxcd.io/cainjector: 'semver:~1'
    filter.fluxcd.io/chart-image: 'semver:~1'
    filter.fluxcd.io/webhook: 'semver:~1'
    fluxcd.io/automated: 'true'
  name: 'cert-manager'
  namespace: 'networking'
spec:
  chart:
    name: 'cert-manager'
    repository: 'https://charts.jetstack.io'
    version: 'v1.0.2'
  releaseName: 'cert-manager'
  values:
    cainjector:
      image:
        repository: 'quay.io/jetstack/cert-manager-cainjector'
        tag: 'v1.0.3'
    image:
      repository: 'quay.io/jetstack/cert-manager-controller'
      tag: 'v1.0.3'
    installCRDs: true
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
    webhook:
      image:
        repository: 'quay.io/jetstack/cert-manager-webhook'
        tag: 'v1.0.3'
