---
apiVersion: 'cert-manager.io/v1'
kind: 'ClusterIssuer'
metadata:
  name: 'letsencrypt'
spec:
  acme:
    email: 'sysadmin@joshuaspence.com'
    privateKeySecretRef:
      name: 'letsencrypt-staging'
    server: 'https://acme-staging-v02.api.letsencrypt.org/directory'
    solvers:
      - dns01:
          route53:
            accessKeyID: 'AKIAUFWWWHZD52ZSO6WC'
            hostedZoneID: 'Z8WQJGKO99WMI'
            region: 'ap-southeast-2'
            secretAccessKeySecretRef:
              key: 'secret-access-key'
              name: 'cert-manager-route53'
        selector:
          dnsZones:
            - 'spence.network'
