---
apiVersion: 'v1'
kind: 'ConfigMap'
metadata:
  name: 'helm-operator-config'
  namespace: 'flux'
data:
  values.yaml: |
    createCRD: false
    helm:
      versions: 'v3'
    prometheus:
      enabled: true
      serviceMonitor:
        create: true
        interval: '30s'
        scrapeTimeout: '10s'
        namespace: 'flux'
    dashboards:
      enabled: true
