---
name: 'Lint'
on: 'push'
jobs:
  eclint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'snow-actions/eclint@v1.0.1'
  hrval:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'stefanprodan/hrval-action@v3.3.1'
        with:
          helmRelease: 'src'
          helmVersion: 'v3'
          kubernetesVersion: 'master'
  kubeval:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'joshuaspence/kubeval-action@38c815e'
        with:
          files: 'src'
          ignored_path_patterns: '\.sops\.yaml$'
          version: 'master'
      - uses: 'joshuaspence/kubeval-action@38c815e'
        with:
          files: 'src'
          ignored_path_patterns: '\.sops\.yaml$'
          version: 'master'

          # NOTE: `kubeval` cannot currently validate CRDs, see
          # https://github.com/instrumenta/kubeval/issues/47.
          additional_schema_locations: 'https://raw.githubusercontent.com/ams0/kubernetes-json-schema/master'

          # NOTE: Strict validation is disabled as the additional schema being
          # used above doesn't support it, see
          # https://github.com/ams0/kubernetes-json-schema/issues/3.
          strict: false
  markdownlint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'avto-dev/markdown-lint@v1'
        with:
          args: '.'
  shellcheck:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'ludeeus/action-shellcheck@0.5.0'
  yamllint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'ibiqlik/action-yamllint@v1'
