---
name: 'Lint'
on: 'push'
jobs:
  eclint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'snow-actions/eclint@v1.0.1'
  hrval:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'stefanprodan/hrval-action@v3.3.1'
        with:
          helmRelease: 'src'
          helmVersion: 'v3'
          kubernetesVersion: 'master'
  kubeval:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'joshuaspence/kubeval-action@master'
        with:
          additional_schema_locations: 'https://raw.githubusercontent.com/joshuaspence/kubernetes-json-schema/master'
          files: 'src'
          ignored_path_patterns: '\.sops\.yaml$'
          version: 'master'
  markdownlint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'avto-dev/markdown-lint@v1'
        with:
          args: '.'
  shellcheck:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'ludeeus/action-shellcheck@0.5.0'
  yamllint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'ibiqlik/action-yamllint@v1'
