---
name: 'Lint'
on: 'push'
jobs:
  eclint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'snow-actions/eclint@v1.0.1'
  hrval:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'stefanprodan/hrval-action@24972b57206860a7843ae6e65fa478d73f169b04'
        with:
          helmRelease: 'src'
          kubernetesVersion: 'master'
          helmVersion: 'v3'
  kubeval:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'instrumenta/kubeval-action@5915e4adba5adccac07cb156b82e54c3fed74921'
        with:
          files: 'src'
          strict: false
          ignore_missing_schemas: true
  shellcheck:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'ludeeus/action-shellcheck@0.4.1'
  yamllint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'ibiqlik/action-yamllint@v1.0.0'
        with:
          strict: true
