---
on:
  push: {}
  pull_request: {}
jobs:
  yamllint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'ibiqlik/action-yamllint@v1.0.0'
        with:
          strict: true

