---
name: 'Lint'
on: 'push'
jobs:
  eclint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'snow-actions/eclint@v1.0.1'
  kubeval:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'instrumenta/kubeval-action@a4e3d91'
        with:
          files: 'src'
          version: 'master'
          ignored_path_patterns: '\.sops\.yaml$'
      - uses: 'stefanprodan/hrval-action@v3.3.1'
        with:
          helmRelease: 'src'
          kubernetesVersion: 'master'
          helmVersion: 'v3'
  markdownlint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'avto-dev/markdown-lint@v1'
        with:
          args: '.'
  shellcheck:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'ludeeus/action-shellcheck@0.5.0'
  yamllint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'ibiqlik/action-yamllint@v1'
        with:
          strict: true
